name: Mearso
markdown: kramdown
exclude: [bower_components, Gemfile, Gemfile.lock, less, '*.json', '*.rb', Gruntfile.js, README.md, node_modules ]

pygments: true
baseurl:  
url:      http://mearso.co.uk
paginate: 5
paginate_path: "/page:num"
permalink:     none


gems:
- jekyll-redirect-from
