# Permalinks
permalink:           none

# Setup
title:               mearso
tagline:             Personal Website of Kevin Mears
url:                 http://www.mearso.co.uk
paginate:            20
paginate_path:  "/blog/page:num/"
baseurl:
highlighter:         rouge
markdown:            kramdown
exclude:             [Gemfile, Gemfile.lock, '*.json', '*.rb', README.md, '.mdastrc', '.htmlhintrc', '.scss-lint.yml', '/node_modules/*', Gruntfile.js, bower_components]
port: 4500

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kevin Mears
  url:               http://www.mearso.co.uk
  email:             mearso@gmail.com
  twitter:           https://twitter.com/mearso
  instagram:         https://www.instagram.com/mearso/
  linkedin:          https://www.linkedin.com/in/kevin-mears-6ab21519/
  google:            https://plus.google.com/u/0/+kevinmears
  letterboxd:        https://letterboxd.com/mearso/

# Custom vars
github:
  repo:              https://github.com/kjmears/kjmears.github.io

manifest_name: Kevin Mears Website
manifest_short_name: Mearso Website # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: en
manifest_background_color: white
manifest_short_name:
manifest_display: standalone

# Gems
plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap

# Collections
collections:
  project:
    description: "College Project"
    output: true
  workshops:
    description: "Workshops"
    output: true
  logospotter:
    description: "Logospotter"
    output: true
    output_tags: true
  styleguide:
    description: "Styleguide"
    output: true
  illustration:
    description: "Illustration"
    output: true
  weeknotes:
    description: "Weeknotes"
    output: true
# Setting some defaults for collections - layouts, collection information.
# with more to follow

defaults:
  - scope:
      path: ""
      type: project
    values:
      layout: project
      info: College Project
  - scope:
      path: ""
      type: workshops
    values:
      layout: workshop
      info: Workshops
  - scope:
      path: ""
      type: logospotter
    values:
      layout: logospotter
      info: Logospotter
  - scope:
      path: ""
      type: styleguide
    values:
      layout: styleguide
      info: Styleguide
  - scope:
      path: ""
      type: illustration
    values:
      layout: default
      info: illustration
  - scope:
      path: ""
      type: weeknotes
    values:
      layout: weeknotes
      info: weeknotes
