# Permalinks
permalink:           none

# Setup
title:               mearso
tagline:             Personal Website of Kevin Mears
url:                 http://www.mearso.co.uk
paginate:            5
paginate_path:  "/blog/page:num/"
baseurl:
highlighter:         rouge
markdown:            kramdown
exclude:             [Gemfile, Gemfile.lock, '*.json', '*.rb', README.md, '.mdastrc', '.htmlhintrc', '.scss-lint.yml', '/node_modules/*' ]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kevin Mears
  url:               https://twitter.com/mearso
  email:             mearso@gmail.com

# Custom vars
github:
  repo:              https://github.com/kjmears/kjmears.github.io

# Gems
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Collections
collections:
  project:
    description: "College Project"
    output: true

# Setting some defaults for collections - layouts, collection information.
# with more to follow

defaults:
  -
    scope:
      path: ""
      type: project
    values:
      layout: project
      info: College Project
