
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4500:4500' # Or '4000:4000' if you prefer the default Jekyll port
    volumes:
      - .:/usr/src/app
    environment:
      JEKYLL_ENV: development