version: '3.4'

services:
  site:
    image: jekyll/jekyll:3.8.6
    command: jekyll serve --livereload --verbose
    ports:
      - 4500:4500
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
