
services:
  jekyll:
    image: jekyll-site:latest
    build:
      context: .
    ports:
      - 4500:4500
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --watch
